[default]
extend-ignore-identifiers-re = [
    "sysmanage",
    "SysManage",
    "bceverly",
    "theeverlys",
    "authn",
    "authz",
    "mTLS",
    "WebSocket",
    "WebSockets",
    "localhost",
    "JSON",
    "HTTP",
    "HTTPS",
    "SSL",
    "TLS",
    "JWT",
    "API",
    "UUID",
    "repo",
    "repos",
    "config",
    "configs",
    "screenshots",
    "admin",
    "sudo",
    "passwd",
    "sudo",
    "systemd",
    "uptime",
    "hostname",
    "username",
    "addr",
    "nginx",
    "apache",
    "postgres",
    "postgresql",
    "docker",
    "kubernetes",
    "ansible",
    "terraform",
    "yaml",
    "yml",
    "toml",
    "json",
    "csv",
    "xml",
    "html",
    "css",
    "javascript",
    "typescript",
    "nodejs",
    "npm",
    "pip",
    "virtualenv",
    "venv",
    "conda",
    "homebrew",
    "chocolatey",
    "winget",
    "scoop",
    "pacman",
    "zypper",
    "portage",
    "pkgsrc",
    "freebsd",
    "openbsd",
    "netbsd",
    "dragonfly",
    "rhel",
    "centos",
    "fedora",
    "debian",
    "ubuntu",
    "suse",
    "opensuse",
    "archlinux",
    "alpine",
    "macos",
    "darwin",
    "linux",
    "unix",
    "posix"
]

[files]
extend-exclude = ["*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg"]