[default]
extend-ignore-identifiers-re = [
    "sysmanage",
    "SysManage",
    "bceverly",
    "theeverlys",
    "authn",
    "authz",
    "mTLS",
    "WebSocket",
    "WebSockets",
    "localhost",
    "JSON",
    "HTTP",
    "HTTPS",
    "SSL",
    "TLS",
    "JWT",
    "API",
    "UUID",
    "repo",
    "repos",
    "config",
    "configs",
    "screenshots",
    "admin",
    "sudo",
    "passwd",
    "sudo",
    "systemd",
    "uptime",
    "hostname",
    "username",
    "addr",
    "nginx",
    "apache",
    "postgres",
    "postgresql",
    "docker",
    "kubernetes",
    "ansible",
    "terraform",
    "yaml",
    "yml",
    "toml",
    "json",
    "csv",
    "xml",
    "html",
    "css",
    "javascript",
    "typescript",
    "nodejs",
    "npm",
    "pip",
    "virtualenv",
    "venv",
    "conda",
    "homebrew",
    "chocolatey",
    "winget",
    "scoop",
    "pacman",
    "zypper",
    "portage",
    "pkgsrc",
    "freebsd",
    "openbsd",
    "netbsd",
    "dragonfly",
    "rhel",
    "centos",
    "fedora",
    "debian",
    "ubuntu",
    "suse",
    "opensuse",
    "archlinux",
    "alpine",
    "macos",
    "darwin",
    "linux",
    "unix",
    "posix",
    "RTO",
    "typ",
    "VAS",
    "OpenVAS",
    "arange",
    "HashiCorp",
    "Hashi",
    "OpenBAO",
    "openbao",
    "bao"
]

[files]
extend-exclude = [
    "*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg",
    "*.js", "*.min.js", "*.min.css",
    "node_modules/**/*",
    ".git/**/*",
    "*.lock", "*.log",
    "package-lock.json",
    "*.woff", "*.woff2", "*.ttf", "*.eot",
    "*.map",
    # Exclude foreign language translation files
    "assets/locales/**/*",
    "frontend/public/locales/**/*",
    "backend/i18n/**/*",
    # Exclude any JSON files with translations
    "**/locales/**/*.json",
    "**/i18n/**/*.json",
    # Exclude typos project documentation (not part of SysManage)
    "doc/**/*",
    # Exclude typos binary
    "typos"
]