# Site settings
title: SysManage
description: Modern system management platform for comprehensive infrastructure monitoring and automation
url: "https://sysmanage.org"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: GitHub
    url: https://github.com/bceverly/sysmanage

# SEO settings
author: SysManage Team
twitter:
  username: sysmanage
  card: summary

logo: /assets/images/sysmanage-logo.svg

# Google Analytics (if needed)
# google_analytics: UA-XXXXXXXXX-X

# Social links
github_username: bceverly