#!/usr/bin/env python3
"""Generate seed_inventory.sql from fixtures.json for the documentation screenshots.

Host hardware (CPU/memory), storage devices, network interfaces, and installed
software have NO REST ingestion path — they normally arrive over the agent
WebSocket and are persisted by a background queue worker. Driving that reliably
from a throwaway fixture proved brittle, so for the screenshots we write the
inventory straight into the tables instead. Deterministic, and fixtures.json
stays the single source of truth.

(OS version is still reported over the WS by fixture_agent.py — that path works —
and OS-upgrade candidates go through the REST updates report in seed.py.)

Writes seed_inventory.sql next to this script; the Makefile applies it inside the
VM via `psql -f /vagrant/seed_inventory.sql`.
"""
from __future__ import annotations

import json
import os
import re
import subprocess

HERE = os.path.dirname(__file__)

# Agent version shown on the demo hosts. Resolved fresh on every run (see main())
# to the most recent bceverly/sysmanage-agent tag via the GitHub API — a simple
# curl, so there's no local agent checkout and no git dependency. The constant
# here is only the offline fallback; override with AGENT_VERSION=x.y.z.
AGENT_VERSION = "1.4.0"


def _latest_agent_tag() -> str | None:
    """Most recent vX.Y.Z(.B) tag of bceverly/sysmanage-agent via the GitHub API.
    Returns the version without a leading 'v', or None on any failure (offline,
    rate-limited, or no version tags)."""
    url = "https://api.github.com/repos/bceverly/sysmanage-agent/tags?per_page=100"
    try:
        res = subprocess.run(
            ["curl", "-fsSL", "-H", "Accept: application/vnd.github+json", url],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if res.returncode != 0:
            return None
        versions = []
        for tag in json.loads(res.stdout):
            match = re.fullmatch(r"v?(\d+(?:\.\d+)+)", (tag.get("name") or "").strip())
            if match:
                versions.append(match.group(1))
        if versions:
            versions.sort(key=lambda v: [int(p) for p in v.split(".")])
            return versions[-1]
    except Exception:
        return None
    return None


def _resolve_agent_version() -> str:
    """AGENT_VERSION env override -> latest sysmanage-agent tag -> offline fallback."""
    env = os.environ.get("AGENT_VERSION")
    if env and env.strip():
        return env.strip()
    return _latest_agent_tag() or AGENT_VERSION


def q(val) -> str:
    """SQL-quote a value (string -> 'escaped', None -> NULL, numbers/bools as-is)."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    return "'" + str(val).replace("'", "''") + "'"


def host_ref(fqdn: str) -> str:
    return f"(SELECT id FROM \"host\" WHERE fqdn={q(fqdn)})"


def first_ipv4(ips: list) -> str | None:
    for ip in ips or []:
        if ":" not in ip:
            return ip
    return None


def main() -> int:
    global AGENT_VERSION
    AGENT_VERSION = _resolve_agent_version()
    print(f"  agent_version (demo hosts) = {AGENT_VERSION}")
    data = json.load(open(os.path.join(HERE, "fixtures.json"), encoding="utf-8"))
    out = [
        "-- GENERATED by gen_seed_sql.py from fixtures.json — do not edit by hand.",
        "-- Seeds host hardware/storage/network/software inventory directly (no REST/WS",
        "-- path exists for these). Idempotent: clears each host's rows first.",
        "",
    ]
    for h in data["hosts"]:
        # The pending-approval host stays as a bare fresh registration (no inventory,
        # no forced "up" status) so it reads as awaiting approval.
        if h.get("approve", True) is False:
            continue
        ref = host_ref(h["fqdn"])
        hw = h.get("hardware", {})
        arch = h.get("architecture")
        out.append(f"-- {h['fqdn']}")
        # OS-version + CPU/memory columns live on the host row; also stamp agent
        # version + up status. (OS columns feed the host-detail "Operating System"
        # pane and the dashboard OS-distribution tile.)
        out.append(
            "UPDATE \"host\" SET "
            f"platform={q(h.get('platform'))}, platform_release={q(h.get('platform_release'))}, "
            f"platform_version={q(h.get('platform_version'))}, "
            f"machine_architecture={q(arch)}, processor={q(arch)}, os_version_updated_at=NOW(), "
            f"cpu_vendor={q(hw.get('cpu_vendor'))}, cpu_model={q(hw.get('cpu_model'))}, "
            f"cpu_cores={q(hw.get('cpu_cores'))}, cpu_threads={q(hw.get('cpu_threads'))}, "
            f"cpu_frequency_mhz={q(hw.get('cpu_frequency_mhz'))}, "
            f"memory_total_mb={q(hw.get('memory_total_mb'))}, "
            f"agent_version={q(AGENT_VERSION)}, status='up', last_access=NOW() "
            f"WHERE fqdn={q(h['fqdn'])};"
        )
        # Storage devices.
        out.append(f"DELETE FROM storage_device WHERE host_id={ref};")
        for d in hw.get("storage_devices", []):
            out.append(
                "INSERT INTO storage_device (id, host_id, device_name, device_type, "
                "mount_point, filesystem, total_size_bytes, used_size_bytes, "
                "available_size_bytes, last_updated) VALUES (gen_random_uuid(), "
                f"{ref}, {q(d.get('name'))}, {q(d.get('device_type'))}, "
                f"{q(d.get('mount_point'))}, {q(d.get('filesystem'))}, "
                f"{q(d.get('total_size'))}, {q(d.get('used_size'))}, "
                f"{q(d.get('available_size'))}, NOW());"
            )
        # Network interfaces.
        out.append(f"DELETE FROM network_interface WHERE host_id={ref};")
        for n in hw.get("network_interfaces", []):
            out.append(
                "INSERT INTO network_interface (id, host_id, interface_name, "
                "mac_address, ipv4_address, netmask, mtu, speed_mbps, is_up, "
                "last_updated) VALUES (gen_random_uuid(), "
                f"{ref}, {q(n.get('name'))}, {q(n.get('mac_address'))}, "
                f"{q(first_ipv4(n.get('ip_addresses')))}, {q(n.get('subnet_mask'))}, "
                f"{q(n.get('mtu'))}, {q(n.get('speed_mbps'))}, "
                f"{q(n.get('is_active'))}, NOW());"
            )
        # Installed software.
        out.append(f"DELETE FROM software_package WHERE host_id={ref};")
        for p in h.get("software", []):
            out.append(
                "INSERT INTO software_package (id, host_id, package_name, "
                "package_version, package_description, package_manager, architecture, "
                "is_system_package, created_at, updated_at) VALUES (gen_random_uuid(), "
                f"{ref}, {q(p.get('package_name'))}, {q(p.get('version'))}, "
                f"{q(p.get('description'))}, {q(p.get('package_manager'))}, "
                f"{q(p.get('architecture'))}, false, NOW(), NOW());"
            )
        # Detected server roles (host-detail "Server Roles" tab). Integer PK is
        # auto-assigned, so it is omitted from the column list.
        out.append(f"DELETE FROM host_roles WHERE host_id={ref};")
        for r in h.get("roles", []):
            out.append(
                "INSERT INTO host_roles (host_id, role, package_name, "
                "package_version, service_name, service_status, is_active, "
                "detected_at, updated_at) VALUES ("
                f"{ref}, {q(r.get('role'))}, {q(r.get('package_name'))}, "
                f"{q(r.get('package_version'))}, {q(r.get('service_name'))}, "
                f"{q(r.get('service_status'))}, {q(r.get('is_active', True))}, "
                "NOW(), NOW());"
            )
        # SSL/TLS certificates (host-detail "Certificates" tab). Validity dates are
        # expressed relative to NOW() in fixtures (not_before_days/not_after_days) so
        # the inventory always looks freshly collected — a negative not_after_days
        # would render as an expired cert.
        out.append(f"DELETE FROM host_certificates WHERE host_id={ref};")
        for c in h.get("certificates", []):
            nb = int(c.get("not_before_days", -30))
            na = int(c.get("not_after_days", 335))
            out.append(
                "INSERT INTO host_certificates (id, host_id, file_path, "
                "certificate_name, subject, issuer, not_before, not_after, "
                "serial_number, fingerprint_sha256, is_ca, key_usage, collected_at, "
                "created_at, updated_at) VALUES (gen_random_uuid(), "
                f"{ref}, {q(c.get('file_path'))}, {q(c.get('certificate_name'))}, "
                f"{q(c.get('subject'))}, {q(c.get('issuer'))}, "
                f"NOW() + ({nb} * INTERVAL '1 day'), "
                f"NOW() + ({na} * INTERVAL '1 day'), "
                f"{q(c.get('serial_number'))}, {q(c.get('fingerprint_sha256'))}, "
                f"{q(c.get('is_ca', False))}, {q(c.get('key_usage'))}, "
                "NOW(), NOW(), NOW());"
            )
        out.append("")

    sql = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "seed_inventory.sql"), "w", encoding="utf-8") as fh:
        fh.write(sql)
    print(f"wrote seed_inventory.sql ({len(data['hosts'])} hosts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
