name: Accessibility Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pa11y
        run: npm install -g pa11y-ci
      - name: Build site
        run: |
          mkdir -p _site
          cp -r docs/* _site/ || cp *.md _site/ 2>/dev/null || true
      - name: Run accessibility tests
        run: pa11y-ci --sitemap http://localhost:3000/sitemap.xml